import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  customType,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import {
  auditActorTypeValues,
  callDirectionValues,
  callStatusValues,
  customFieldEntityValues,
  customFieldTypeValues,
  emailDirectionValues,
  emailProviderValues,
  noteStatusValues,
  opportunityStatusValues,
  sequenceEnrollmentStateValues,
  sequenceStatusValues,
  sequenceStepTypeValues,
  sendIntentStateValues,
  smsDirectionValues,
  suppressionKindValues,
  suppressionSourceValues,
  syncStatusValues,
  templateChannelValues,
  threadTriageValues,
  userRoleValues,
  webhookDeliveryStateValues,
  webhookProviderValues,
} from '@switchboard/shared';
import { ACTIVITY_TYPES } from '@switchboard/shared';

/**
 * Drizzle schema — the persistence shape for CONTRACTS §C1 (normative). String
 * unions come from `@switchboard/shared` so column enums and API DTO enums share
 * one source of truth. Conventions (§C1): uuid PKs `gen_random_uuid()`, all
 * timestamps `timestamptz`, every table `created_at`/`updated_at`, FKs
 * `on delete restrict` unless stated, soft delete (`deleted_at`) only where the
 * contract marks it.
 *
 * Real SQL migrations are generated by drizzle-kit from THIS file
 * (`pnpm --filter @switchboard/api db:generate`); the `citext`/`pgcrypto`
 * extensions are enabled by the hand-authored bootstrap migration that runs
 * first (see `migrations/0000_*.sql`).
 */

// --- Custom column types ----------------------------------------------------

/** Case-insensitive text (Postgres `citext` extension). */
const citext = customType<{ data: string }>({
  dataType() {
    return 'citext';
  },
});

/** Full-text search vector (Postgres `tsvector`). */
const tsvector = customType<{ data: string }>({
  dataType() {
    return 'tsvector';
  },
});

// --- Reusable column groups -------------------------------------------------

function id() {
  return uuid('id').primaryKey().defaultRandom();
}

function tstz(name: string) {
  return timestamp(name, { withTimezone: true, mode: 'string' });
}

function timestamps() {
  return {
    createdAt: tstz('created_at').notNull().defaultNow(),
    updatedAt: tstz('updated_at').notNull().defaultNow(),
  };
}

// --- Dimension tables -------------------------------------------------------

export const users = pgTable(
  'users',
  {
    id: id(),
    email: citext('email').notNull(),
    name: text('name').notNull(),
    role: text('role', { enum: userRoleValues }).notNull(),
    idpSubject: text('idp_subject').notNull(),
    isActive: boolean('is_active').notNull().default(true),
    timezone: text('timezone').notNull().default('UTC'),
    ...timestamps(),
  },
  (t) => [
    uniqueIndex('users_email_key').on(t.email),
    uniqueIndex('users_idp_subject_key').on(t.idpSubject),
  ],
);

export const leadStatuses = pgTable('lead_statuses', {
  id: id(),
  label: text('label').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
  ...timestamps(),
});

export const opportunityStages = pgTable('opportunity_stages', {
  id: id(),
  label: text('label').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
  ...timestamps(),
});

// --- Core CRM tables --------------------------------------------------------

export const leads = pgTable(
  'leads',
  {
    id: id(),
    name: text('name').notNull(),
    url: text('url'),
    description: text('description'),
    statusId: uuid('status_id').references(() => leadStatuses.id, { onDelete: 'restrict' }),
    ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'restrict' }),
    custom: jsonb('custom').$type<Record<string, unknown>>().notNull().default({}),
    // Denormalized hot columns — event-writer maintained (CONTRACTS §C4 / §9).
    lastContactedAt: tstz('last_contacted_at'),
    lastInboundAt: tstz('last_inbound_at'),
    nextTaskDueAt: tstz('next_task_due_at'),
    lastCallAt: tstz('last_call_at'),
    lastEmailAt: tstz('last_email_at'),
    lastSmsAt: tstz('last_sms_at'),
    dnc: boolean('dnc').notNull().default(false),
    searchTsv: tsvector('search_tsv').generatedAlwaysAs(
      sql`to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))`,
    ),
    // Trigram source (global search 1e): lowercased name + url + description.
    // Backs substring/typo matching the FTS vector can't (e.g. a fragment inside
    // a URL, or the company slug embedded in a domain). GIN-trigram indexed below.
    searchText: text('search_text').generatedAlwaysAs(
      sql`lower(coalesce(name, '') || ' ' || coalesce(url, '') || ' ' || coalesce(description, ''))`,
    ),
    deletedAt: tstz('deleted_at'),
    ...timestamps(),
  },
  (t) => [
    index('leads_owner_id_idx').on(t.ownerId),
    index('leads_status_id_idx').on(t.statusId),
    // Denormalized hot-column indexes (Task 1c / ARCHITECTURE §9). Smart View
    // date/activity predicates hit these first; every list read filters
    // `deleted_at IS NULL`, so the indexes are partial on the live set (smaller,
    // and the planner uses them whenever the query carries that predicate).
    index('leads_last_contacted_at_idx')
      .on(t.lastContactedAt)
      .where(sql`${t.deletedAt} IS NULL`),
    index('leads_last_inbound_at_idx')
      .on(t.lastInboundAt)
      .where(sql`${t.deletedAt} IS NULL`),
    index('leads_next_task_due_at_idx')
      .on(t.nextTaskDueAt)
      .where(sql`${t.deletedAt} IS NULL`),
    index('leads_last_call_at_idx')
      .on(t.lastCallAt)
      .where(sql`${t.deletedAt} IS NULL`),
    index('leads_last_email_at_idx')
      .on(t.lastEmailAt)
      .where(sql`${t.deletedAt} IS NULL`),
    index('leads_last_sms_at_idx')
      .on(t.lastSmsAt)
      .where(sql`${t.deletedAt} IS NULL`),
    // Custom-field containment (GIN, jsonb_path_ops — compact, `@>`-optimized).
    // Per-field expression indexes for select/date/number keys are added later by
    // the field-definition service (ARCHITECTURE §9); this is the general index.
    index('leads_custom_gin_idx').using('gin', t.custom.op('jsonb_path_ops')),
    // Full-text search vector (global search 1e + DSL `matches` clause).
    index('leads_search_tsv_gin_idx').using('gin', t.searchTsv),
    // Trigram indexes (global search 1e): `name %` similarity/typo path and the
    // substring (`search_text LIKE '%q%'`) path — both index-backed via pg_trgm.
    index('leads_name_trgm_idx').using('gin', t.name.op('gin_trgm_ops')),
    index('leads_search_text_trgm_idx').using('gin', t.searchText.op('gin_trgm_ops')),
  ],
);

export const contacts = pgTable(
  'contacts',
  {
    id: id(),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    name: text('name').notNull(),
    title: text('title'),
    emails: jsonb('emails').$type<{ email: string; type: string }[]>().notNull().default([]),
    phones: jsonb('phones').$type<{ phone: string; type: string }[]>().notNull().default([]),
    dnc: boolean('dnc').notNull().default(false),
    // Search columns (global search 1e). Emails/phones are jsonb arrays of
    // objects; a generated column can't use a subquery, so the address/number
    // strings are pulled with the immutable `jsonb_path_query_array` and the
    // JSON punctuation (`[`, `]`, `"`, `,`) is blanked with `translate` — leaving
    // the raw values as space-separated tokens the FTS parser recognises (emails
    // survive as single tokens) and the trigram index can substring-match.
    searchTsv: tsvector('search_tsv').generatedAlwaysAs(
      sql`to_tsvector('english', coalesce(name, '') || ' ' || coalesce(title, '') || ' ' || translate(coalesce(jsonb_path_query_array(emails, '$[*].email')::text, ''), '[]",', '    ') || ' ' || translate(coalesce(jsonb_path_query_array(phones, '$[*].phone')::text, ''), '[]",', '    '))`,
    ),
    searchText: text('search_text').generatedAlwaysAs(
      sql`lower(coalesce(name, '') || ' ' || coalesce(title, '') || ' ' || translate(coalesce(jsonb_path_query_array(emails, '$[*].email')::text, ''), '[]",', '    ') || ' ' || translate(coalesce(jsonb_path_query_array(phones, '$[*].phone')::text, ''), '[]",', '    '))`,
    ),
    deletedAt: tstz('deleted_at'),
    ...timestamps(),
  },
  (t) => [
    index('contacts_lead_id_idx').on(t.leadId),
    // Full-text over name/title/email/phone tokens (global search 1e).
    index('contacts_search_tsv_gin_idx').using('gin', t.searchTsv),
    // Trigram: `name %` similarity/typo path and `search_text LIKE '%q%'`
    // substring path (email fragments, phone substrings).
    index('contacts_name_trgm_idx').using('gin', t.name.op('gin_trgm_ops')),
    index('contacts_search_text_trgm_idx').using('gin', t.searchText.op('gin_trgm_ops')),
  ],
);

export const opportunities = pgTable('opportunities', {
  id: id(),
  leadId: uuid('lead_id')
    .notNull()
    .references(() => leads.id, { onDelete: 'restrict' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'restrict' }),
  valueCents: bigint('value_cents', { mode: 'number' }).notNull().default(0),
  currency: char('currency', { length: 3 }).notNull().default('USD'),
  stageId: uuid('stage_id').references(() => opportunityStages.id, { onDelete: 'restrict' }),
  confidence: integer('confidence').notNull().default(0),
  closeDate: date('close_date'),
  ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'restrict' }),
  status: text('status', { enum: opportunityStatusValues }).notNull().default('active'),
  note: text('note'),
  ...timestamps(),
});

export const customFieldDefs = pgTable(
  'custom_field_defs',
  {
    id: id(),
    entity: text('entity', { enum: customFieldEntityValues }).notNull(),
    key: text('key').notNull(),
    label: text('label').notNull(),
    type: text('type', { enum: customFieldTypeValues }).notNull(),
    options: jsonb('options').$type<unknown[]>(),
    required: boolean('required').notNull().default(false),
    ...timestamps(),
  },
  (t) => [uniqueIndex('custom_field_defs_entity_key_key').on(t.entity, t.key)],
);

/**
 * THE spine (CONTRACTS §C1/§C4). Append-only: only the ActivityWriter service
 * inserts here, and no column is ever updated (corrections are new
 * `activity_correction` rows). `type` is TS-narrowed to the taxonomy; DB stores
 * it as text.
 */
export const activities = pgTable(
  'activities',
  {
    id: id(),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'restrict' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'restrict' }),
    type: text('type', { enum: ACTIVITY_TYPES }).notNull(),
    occurredAt: tstz('occurred_at').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
    ...timestamps(),
  },
  (t) => [
    // Timeline read path: (lead_id, occurred_at DESC, id) covering index.
    index('activities_lead_occurred_idx').on(t.leadId, t.occurredAt.desc(), t.id),
    // Type-filtered EXISTS path (Task 1c): DSL activity predicates that fall back
    // to the spine (note / task_completed / sequence) filter by (lead_id, type)
    // then range on occurred_at.
    index('activities_lead_type_occurred_idx').on(t.leadId, t.type, t.occurredAt.desc()),
  ],
);

export const tasks = pgTable(
  'tasks',
  {
    id: id(),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    assigneeId: uuid('assignee_id').references(() => users.id, { onDelete: 'restrict' }),
    title: text('title').notNull(),
    dueAt: tstz('due_at'),
    completedAt: tstz('completed_at'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'restrict' }),
    ...timestamps(),
  },
  (t) => [
    index('tasks_lead_id_idx').on(t.leadId),
    // Inbox read (Task 1c): open tasks due for a user. Partial on the open set
    // keeps the index small (completed tasks dominate over time).
    index('tasks_open_due_idx')
      .on(t.assigneeId, t.dueAt)
      .where(sql`${t.completedAt} IS NULL`),
  ],
);

export const notes = pgTable('notes', {
  id: id(),
  leadId: uuid('lead_id')
    .notNull()
    .references(() => leads.id, { onDelete: 'restrict' }),
  authorId: uuid('author_id').references(() => users.id, { onDelete: 'restrict' }),
  bodyMd: text('body_md').notNull().default(''),
  status: text('status', { enum: noteStatusValues }).notNull().default('draft'),
  aiGenerated: boolean('ai_generated').notNull().default(false),
  ...timestamps(),
});

// --- Email -----------------------------------------------------------------

export const emailAccounts = pgTable('email_accounts', {
  id: id(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'restrict' }),
  address: citext('address').notNull(),
  provider: text('provider', { enum: emailProviderValues }).notNull(),
  oauthTokens: text('oauth_tokens'),
  syncStatus: text('sync_status', { enum: syncStatusValues }).notNull().default('UNLINKED'),
  historyCursor: text('history_cursor'),
  backfillCheckpoint: jsonb('backfill_checkpoint').$type<Record<string, unknown>>(),
  dailySendCount: integer('daily_send_count').notNull().default(0),
  dailyCountDate: date('daily_count_date'),
  ...timestamps(),
});

export const emailThreads = pgTable(
  'email_threads',
  {
    id: id(),
    leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'restrict' }),
    subjectNorm: text('subject_norm'),
    participants: jsonb('participants').$type<unknown[]>().notNull().default([]),
    triageStatus: text('triage_status', { enum: threadTriageValues })
      .notNull()
      .default('ambiguous'),
    providerThreadId: text('provider_thread_id'),
    ...timestamps(),
  },
  (t) => [
    // Triage queue (Task 1c): the actionable set is the ambiguous threads awaiting
    // a match decision; partial keeps it tight as matched threads accumulate.
    index('email_threads_triage_idx')
      .on(t.triageStatus, t.leadId)
      .where(sql`${t.triageStatus} = 'ambiguous'`),
  ],
);

export const emailMessages = pgTable(
  'email_messages',
  {
    id: id(),
    accountId: uuid('account_id')
      .notNull()
      .references(() => emailAccounts.id, { onDelete: 'restrict' }),
    providerMessageId: text('provider_message_id'),
    rfcMessageId: text('rfc_message_id'),
    threadId: uuid('thread_id').references(() => emailThreads.id, { onDelete: 'restrict' }),
    direction: text('direction', { enum: emailDirectionValues }).notNull(),
    fromAddr: text('from_addr'),
    toAddrs: jsonb('to_addrs').$type<unknown[]>().notNull().default([]),
    cc: jsonb('cc').$type<unknown[]>().notNull().default([]),
    subject: text('subject'),
    snippet: text('snippet'),
    bodyRef: text('body_ref'),
    sentAt: tstz('sent_at'),
    inReplyTo: text('in_reply_to'),
    refs: jsonb('refs').$type<unknown[]>().notNull().default([]),
    ...timestamps(),
  },
  (t) => [
    // The dedupe backstop (CONTRACTS §C1) + per-account provider id uniqueness.
    uniqueIndex('email_messages_account_rfc_key').on(t.accountId, t.rfcMessageId),
    uniqueIndex('email_messages_account_provider_key').on(t.accountId, t.providerMessageId),
  ],
);

// --- Templates / snippets ---------------------------------------------------

export const templates = pgTable('templates', {
  id: id(),
  name: text('name').notNull(),
  channel: text('channel', { enum: templateChannelValues }).notNull(),
  subject: text('subject'),
  body: text('body').notNull().default(''),
  ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'restrict' }),
  shared: boolean('shared').notNull().default(false),
  ...timestamps(),
});

export const snippets = pgTable('snippets', {
  id: id(),
  shortcut: text('shortcut').notNull(),
  body: text('body').notNull().default(''),
  ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'restrict' }),
  ...timestamps(),
});

// --- Sequences --------------------------------------------------------------

export const sequences = pgTable('sequences', {
  id: id(),
  name: text('name').notNull(),
  status: text('status', { enum: sequenceStatusValues }).notNull().default('active'),
  settings: jsonb('settings').$type<Record<string, unknown>>().notNull().default({}),
  ...timestamps(),
});

export const sequenceSteps = pgTable('sequence_steps', {
  id: id(),
  sequenceId: uuid('sequence_id')
    .notNull()
    .references(() => sequences.id, { onDelete: 'restrict' }),
  sortOrder: integer('sort_order').notNull().default(0),
  type: text('type', { enum: sequenceStepTypeValues }).notNull(),
  delayHours: integer('delay_hours').notNull().default(0),
  templateId: uuid('template_id').references(() => templates.id, { onDelete: 'restrict' }),
  requiresReview: boolean('requires_review').notNull().default(false),
  condition: jsonb('condition').$type<Record<string, unknown>>(),
  ...timestamps(),
});

export const sequenceEnrollments = pgTable(
  'sequence_enrollments',
  {
    id: id(),
    sequenceId: uuid('sequence_id')
      .notNull()
      .references(() => sequences.id, { onDelete: 'restrict' }),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    contactId: uuid('contact_id')
      .notNull()
      .references(() => contacts.id, { onDelete: 'restrict' }),
    emailAccountId: uuid('email_account_id').references(() => emailAccounts.id, {
      onDelete: 'restrict',
    }),
    enrolledBy: uuid('enrolled_by').references(() => users.id, { onDelete: 'restrict' }),
    state: text('state', { enum: sequenceEnrollmentStateValues }).notNull().default('active'),
    pausedReason: text('paused_reason'),
    ...timestamps(),
  },
  (t) => [
    // One live enrollment per (sequence, contact) — partial unique on state.
    uniqueIndex('sequence_enrollments_seq_contact_live_key')
      .on(t.sequenceId, t.contactId)
      .where(sql`${t.state} in ('active', 'paused')`),
  ],
);

export const sendIntents = pgTable(
  'send_intents',
  {
    id: id(),
    enrollmentId: uuid('enrollment_id')
      .notNull()
      .references(() => sequenceEnrollments.id, { onDelete: 'restrict' }),
    stepId: uuid('step_id')
      .notNull()
      .references(() => sequenceSteps.id, { onDelete: 'restrict' }),
    channel: text('channel', { enum: sequenceStepTypeValues }).notNull(),
    dueAt: tstz('due_at').notNull(),
    state: text('state', { enum: sendIntentStateValues }).notNull().default('SCHEDULED'),
    claimedAt: tstz('claimed_at'),
    workerId: text('worker_id'),
    sentAt: tstz('sent_at'),
    providerMessageId: text('provider_message_id'),
    skipReason: text('skip_reason'),
    ...timestamps(),
  },
  (t) => [
    // Never-sends-twice backstop (CONTRACTS §C1/§C6 I-SEND-1).
    uniqueIndex('send_intents_enrollment_step_key').on(t.enrollmentId, t.stepId),
    // Sweeper scan (Task 1c / ARCHITECTURE §4): find due intents by state+due_at
    // (SCHEDULED to enqueue, CLAIMED to expire).
    index('send_intents_state_due_idx').on(t.state, t.dueAt),
  ],
);

// --- Compliance / suppression ----------------------------------------------

export const suppressions = pgTable(
  'suppressions',
  {
    id: id(),
    kind: text('kind', { enum: suppressionKindValues }).notNull(),
    value: citext('value').notNull(),
    source: text('source', { enum: suppressionSourceValues }).notNull(),
    reason: text('reason'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'restrict' }),
    releasedAt: tstz('released_at'),
    releasedBy: uuid('released_by').references(() => users.id, { onDelete: 'restrict' }),
    releaseReason: text('release_reason'),
    ...timestamps(),
  },
  (t) => [
    uniqueIndex('suppressions_kind_value_key').on(t.kind, t.value),
    // Compliance hot path (Task 1c / CONTRACTS §C6): the send/dial transaction
    // checks for an *active* suppression by (kind, value); partial on the
    // not-yet-released set keeps the probe index small.
    index('suppressions_active_lookup_idx')
      .on(t.kind, t.value)
      .where(sql`${t.releasedAt} IS NULL`),
  ],
);

// --- Telephony -------------------------------------------------------------

export const calls = pgTable(
  'calls',
  {
    id: id(),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'restrict' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'restrict' }),
    direction: text('direction', { enum: callDirectionValues }).notNull(),
    twilioSid: text('twilio_sid'),
    status: text('status', { enum: callStatusValues }).notNull(),
    durationS: integer('duration_s'),
    outcome: text('outcome'),
    recordingRef: text('recording_ref'),
    transcriptRef: text('transcript_ref'),
    startedAt: tstz('started_at'),
    endedAt: tstz('ended_at'),
    ...timestamps(),
  },
  (t) => [uniqueIndex('calls_twilio_sid_key').on(t.twilioSid)],
);

export const smsMessages = pgTable(
  'sms_messages',
  {
    id: id(),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'restrict' }),
    contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'restrict' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'restrict' }),
    direction: text('direction', { enum: smsDirectionValues }).notNull(),
    fromNumber: text('from_number').notNull(),
    toNumber: text('to_number').notNull(),
    body: text('body').notNull().default(''),
    providerSid: text('provider_sid'),
    status: text('status').notNull(),
    sentAt: tstz('sent_at'),
    ...timestamps(),
  },
  (t) => [uniqueIndex('sms_messages_provider_sid_key').on(t.providerSid)],
);

// --- Smart views / webhooks / tokens / audit -------------------------------

export const smartViews = pgTable('smart_views', {
  id: id(),
  name: text('name').notNull(),
  ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'restrict' }),
  shared: boolean('shared').notNull().default(false),
  dsl: text('dsl').notNull().default(''),
  ast: jsonb('ast').$type<Record<string, unknown>>().notNull().default({}),
  sort: jsonb('sort').$type<Record<string, unknown>>(),
  columns: jsonb('columns').$type<unknown[]>(),
  ...timestamps(),
});

export const webhookInbox = pgTable(
  'webhook_inbox',
  {
    id: id(),
    provider: text('provider', { enum: webhookProviderValues }).notNull(),
    providerEventId: text('provider_event_id').notNull(),
    raw: jsonb('raw').$type<Record<string, unknown>>().notNull().default({}),
    receivedAt: tstz('received_at').notNull().defaultNow(),
    processedAt: tstz('processed_at'),
    error: text('error'),
    ...timestamps(),
  },
  (t) => [uniqueIndex('webhook_inbox_provider_event_key').on(t.provider, t.providerEventId)],
);

export const webhookSubscriptions = pgTable('webhook_subscriptions', {
  id: id(),
  url: text('url').notNull(),
  secret: text('secret').notNull(),
  events: jsonb('events').$type<unknown[]>().notNull().default([]),
  isActive: boolean('is_active').notNull().default(true),
  ...timestamps(),
});

export const webhookDeliveries = pgTable('webhook_deliveries', {
  id: id(),
  subscriptionId: uuid('subscription_id')
    .notNull()
    .references(() => webhookSubscriptions.id, { onDelete: 'restrict' }),
  event: jsonb('event').$type<Record<string, unknown>>().notNull().default({}),
  state: text('state', { enum: webhookDeliveryStateValues }).notNull().default('pending'),
  attempts: integer('attempts').notNull().default(0),
  nextRetryAt: tstz('next_retry_at'),
  ...timestamps(),
});

export const apiTokens = pgTable(
  'api_tokens',
  {
    id: id(),
    name: text('name').notNull(),
    hash: text('hash').notNull(),
    scopes: jsonb('scopes').$type<unknown[]>().notNull().default([]),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'restrict' }),
    lastUsedAt: tstz('last_used_at'),
    revokedAt: tstz('revoked_at'),
    ...timestamps(),
  },
  (t) => [uniqueIndex('api_tokens_hash_key').on(t.hash)],
);

export const auditLog = pgTable('audit_log', {
  id: id(),
  actorId: uuid('actor_id').references(() => users.id, { onDelete: 'restrict' }),
  actorType: text('actor_type', { enum: auditActorTypeValues }).notNull(),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: uuid('entity_id'),
  before: jsonb('before').$type<Record<string, unknown>>(),
  after: jsonb('after').$type<Record<string, unknown>>(),
  reason: text('reason'),
  ip: text('ip'),
  at: tstz('at').notNull().defaultNow(),
  ...timestamps(),
});

export const orgSettings = pgTable('org_settings', {
  id: id(),
  recordingEnabled: boolean('recording_enabled').notNull().default(false),
  recordingEnabledBy: uuid('recording_enabled_by').references(() => users.id, {
    onDelete: 'restrict',
  }),
  recordingLegalSignoffRef: text('recording_legal_signoff_ref'),
  quietHours: jsonb('quiet_hours').$type<Record<string, unknown>>(),
  sendingWindow: jsonb('sending_window').$type<Record<string, unknown>>(),
  dailySendCap: integer('daily_send_cap').notNull().default(200),
  companyTimezone: text('company_timezone').notNull().default('UTC'),
  ...timestamps(),
});

export const syncEvents = pgTable('sync_events', {
  id: id(),
  accountId: uuid('account_id')
    .notNull()
    .references(() => emailAccounts.id, { onDelete: 'restrict' }),
  fromState: text('from_state', { enum: syncStatusValues }),
  toState: text('to_state', { enum: syncStatusValues }).notNull(),
  cause: text('cause').notNull(),
  at: tstz('at').notNull().defaultNow(),
  ...timestamps(),
});

// --- Imports (CSV import engine, Task 4f / CONTRACTS §C1 v1.1.0, D-018) ------

/**
 * Import status lifecycle (CONTRACTS §C1 `imports.status`):
 * `uploaded → mapped → dry_run → committing → committed`, with `failed` reachable
 * from any active state. Defined here rather than in `@switchboard/shared` only
 * because Task 4f's allowlist excludes the shared package; it is otherwise a
 * single-source-of-truth enum like the domain.ts ones and should be hoisted to
 * shared at merge (reported as friction).
 */
export const importStatusValues = [
  'uploaded',
  'mapped',
  'dry_run',
  'committing',
  'committed',
  'failed',
] as const;

/**
 * CSV import jobs (CONTRACTS §C1, added v1.1.0 / migration 0010). One row per
 * uploaded file; `mapping`/`dedupe_config` are set at dry-run time, `dry_run_result`
 * holds the persisted per-row plan + aggregate counts, and `result` carries the
 * commit checkpoint (resumable, crash-safe) and final counts. `file_ref` points at
 * the stored raw CSV (local disk under MOCK_MODE; object storage in deploy).
 */
export const imports = pgTable(
  'imports',
  {
    id: id(),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    filename: text('filename').notNull(),
    fileRef: text('file_ref').notNull(),
    rowCount: integer('row_count'),
    status: text('status', { enum: importStatusValues }).notNull().default('uploaded'),
    mapping: jsonb('mapping').$type<Record<string, unknown>>(),
    dedupeConfig: jsonb('dedupe_config').$type<Record<string, unknown>>(),
    dryRunResult: jsonb('dry_run_result').$type<Record<string, unknown>>(),
    result: jsonb('result').$type<Record<string, unknown>>(),
    error: text('error'),
    ...timestamps(),
  },
  (t) => [index('imports_created_by_idx').on(t.createdBy)],
);

// --- Row type inference (persistence shapes) -------------------------------

export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;
export type LeadRow = typeof leads.$inferSelect;
export type NewLeadRow = typeof leads.$inferInsert;
export type ContactRow = typeof contacts.$inferSelect;
export type NewContactRow = typeof contacts.$inferInsert;
export type OpportunityRow = typeof opportunities.$inferSelect;
export type NewOpportunityRow = typeof opportunities.$inferInsert;
export type ActivityRow = typeof activities.$inferSelect;
export type NewActivityRow = typeof activities.$inferInsert;
export type TaskRow = typeof tasks.$inferSelect;
export type NewTaskRow = typeof tasks.$inferInsert;
export type LeadStatusRow = typeof leadStatuses.$inferSelect;
export type OpportunityStageRow = typeof opportunityStages.$inferSelect;
export type SuppressionRow = typeof suppressions.$inferSelect;
export type ImportRow = typeof imports.$inferSelect;
export type NewImportRow = typeof imports.$inferInsert;
