import { phoneMatchKey } from '../telephony/phone.ts';

/**
 * NANP area-code → IANA timezone inference for the I-QUIET recipient-local check
 * (CONTRACTS §C6: "recipient-local, area-code inferred, fallback company tz"). A
 * US/Canada number's leading 3-digit area code (NPA) maps to the timezone of its
 * numbering-plan region; when the number is non-NANP, too short, or an unmapped
 * NPA, inference returns null and the caller falls back to the company timezone.
 *
 * This is a documented v1 approximation: number portability and overlays mean an
 * area code is a heuristic for the subscriber's actual location, not a guarantee.
 * The fallback (company tz) is always safe, and the map covers the common US NPAs
 * across all five continental zones plus Alaska/Hawaii. Revisit (a carrier lookup)
 * only with a documented rep-facing complaint.
 *
 * No enums / namespaces / parameter properties (host type-stripping constraint).
 */

/** Area code (NPA) → IANA zone. Curated set of common US/Canada NPAs. */
const AREA_CODE_TZ: Readonly<Record<string, string>> = {
  // --- Eastern (America/New_York) ---
  '201': 'America/New_York',
  '202': 'America/New_York',
  '203': 'America/New_York',
  '212': 'America/New_York',
  '215': 'America/New_York',
  '216': 'America/New_York',
  '240': 'America/New_York',
  '267': 'America/New_York',
  '301': 'America/New_York',
  '302': 'America/New_York',
  '305': 'America/New_York',
  '404': 'America/New_York',
  '407': 'America/New_York',
  '410': 'America/New_York',
  '412': 'America/New_York',
  '413': 'America/New_York',
  '419': 'America/New_York',
  '440': 'America/New_York',
  '470': 'America/New_York',
  '475': 'America/New_York',
  '516': 'America/New_York',
  '518': 'America/New_York',
  '561': 'America/New_York',
  '585': 'America/New_York',
  '607': 'America/New_York',
  '610': 'America/New_York',
  '614': 'America/New_York',
  '617': 'America/New_York',
  '646': 'America/New_York',
  '678': 'America/New_York',
  '703': 'America/New_York',
  '704': 'America/New_York',
  '716': 'America/New_York',
  '718': 'America/New_York',
  '724': 'America/New_York',
  '732': 'America/New_York',
  '754': 'America/New_York',
  '757': 'America/New_York',
  '770': 'America/New_York',
  '786': 'America/New_York',
  '804': 'America/New_York',
  '813': 'America/New_York',
  '814': 'America/New_York',
  '845': 'America/New_York',
  '854': 'America/New_York',
  '860': 'America/New_York',
  '863': 'America/New_York',
  '904': 'America/New_York',
  '908': 'America/New_York',
  '914': 'America/New_York',
  '917': 'America/New_York',
  '919': 'America/New_York',
  '929': 'America/New_York',
  '954': 'America/New_York',
  // --- Central (America/Chicago) ---
  '205': 'America/Chicago',
  '210': 'America/Chicago',
  '214': 'America/Chicago',
  '224': 'America/Chicago',
  '225': 'America/Chicago',
  '251': 'America/Chicago',
  '262': 'America/Chicago',
  '281': 'America/Chicago',
  '309': 'America/Chicago',
  '312': 'America/Chicago',
  '314': 'America/Chicago',
  '316': 'America/Chicago',
  '318': 'America/Chicago',
  '319': 'America/Chicago',
  '331': 'America/Chicago',
  '337': 'America/Chicago',
  '346': 'America/Chicago',
  '361': 'America/Chicago',
  '402': 'America/Chicago',
  '405': 'America/Chicago',
  '414': 'America/Chicago',
  '417': 'America/Chicago',
  '469': 'America/Chicago',
  '479': 'America/Chicago',
  '501': 'America/Chicago',
  '504': 'America/Chicago',
  '512': 'America/Chicago',
  '515': 'America/Chicago',
  '563': 'America/Chicago',
  '573': 'America/Chicago',
  '601': 'America/Chicago',
  '608': 'America/Chicago',
  '612': 'America/Chicago',
  '615': 'America/Chicago',
  '618': 'America/Chicago',
  '630': 'America/Chicago',
  '636': 'America/Chicago',
  '651': 'America/Chicago',
  '682': 'America/Chicago',
  '708': 'America/Chicago',
  '713': 'America/Chicago',
  '715': 'America/Chicago',
  '763': 'America/Chicago',
  '769': 'America/Chicago',
  '773': 'America/Chicago',
  '779': 'America/Chicago',
  '815': 'America/Chicago',
  '816': 'America/Chicago',
  '817': 'America/Chicago',
  '832': 'America/Chicago',
  '847': 'America/Chicago',
  '901': 'America/Chicago',
  '913': 'America/Chicago',
  '915': 'America/Chicago',
  '918': 'America/Chicago',
  '920': 'America/Chicago',
  '936': 'America/Chicago',
  '940': 'America/Chicago',
  '952': 'America/Chicago',
  '956': 'America/Chicago',
  '972': 'America/Chicago',
  // --- Mountain (America/Denver) ---
  '303': 'America/Denver',
  '307': 'America/Denver',
  '385': 'America/Denver',
  '406': 'America/Denver',
  '505': 'America/Denver',
  '575': 'America/Denver',
  '719': 'America/Denver',
  '720': 'America/Denver',
  '801': 'America/Denver',
  '970': 'America/Denver',
  // --- Arizona (no DST, America/Phoenix) ---
  '480': 'America/Phoenix',
  '520': 'America/Phoenix',
  '602': 'America/Phoenix',
  '623': 'America/Phoenix',
  '928': 'America/Phoenix',
  // --- Pacific (America/Los_Angeles) ---
  '206': 'America/Los_Angeles',
  '209': 'America/Los_Angeles',
  '213': 'America/Los_Angeles',
  '253': 'America/Los_Angeles',
  '310': 'America/Los_Angeles',
  '323': 'America/Los_Angeles',
  '360': 'America/Los_Angeles',
  '408': 'America/Los_Angeles',
  '415': 'America/Los_Angeles',
  '424': 'America/Los_Angeles',
  '425': 'America/Los_Angeles',
  '442': 'America/Los_Angeles',
  '503': 'America/Los_Angeles',
  '509': 'America/Los_Angeles',
  '510': 'America/Los_Angeles',
  '530': 'America/Los_Angeles',
  '541': 'America/Los_Angeles',
  '559': 'America/Los_Angeles',
  '562': 'America/Los_Angeles',
  '619': 'America/Los_Angeles',
  '626': 'America/Los_Angeles',
  '650': 'America/Los_Angeles',
  '661': 'America/Los_Angeles',
  '669': 'America/Los_Angeles',
  '702': 'America/Los_Angeles',
  '707': 'America/Los_Angeles',
  '714': 'America/Los_Angeles',
  '725': 'America/Los_Angeles',
  '747': 'America/Los_Angeles',
  '760': 'America/Los_Angeles',
  '775': 'America/Los_Angeles',
  '805': 'America/Los_Angeles',
  '818': 'America/Los_Angeles',
  '831': 'America/Los_Angeles',
  '858': 'America/Los_Angeles',
  '909': 'America/Los_Angeles',
  '916': 'America/Los_Angeles',
  '925': 'America/Los_Angeles',
  '949': 'America/Los_Angeles',
  '951': 'America/Los_Angeles',
  '971': 'America/Los_Angeles',
  // --- Alaska / Hawaii ---
  '907': 'America/Anchorage',
  '808': 'Pacific/Honolulu',
};

/**
 * Infer a recipient IANA timezone from a phone number's NANP area code, or null
 * when the number is not a recognizable 10-digit NANP number or the NPA is
 * unmapped. Uses the same trailing-10-digit normalization as the rest of the
 * telephony path (`phoneMatchKey`), so `+1 (305) 555-0147` and `3055550147`
 * resolve identically.
 */
export function inferTimezoneFromNumber(phone: string): string | null {
  const key = phoneMatchKey(phone);
  if (key === '') return null;
  const npa = key.slice(0, 3);
  return AREA_CODE_TZ[npa] ?? null;
}
